Creación de variables dummmy y particionamiento del dataset
===

* *60:00 min* | Última modificación: Agosto 13, 2021 | YouTube

Una tabla gestionada en Pandas puede ser usada como datos para el entrenamiento de modelos en machine learning. En esta lección se abordan problemas específicos de esta tarea.

![esquema-modelado](assets/esquema-modelado-ml.png)

Al finalizar el documento, usted estará en capacidad de:

* Crear variables dummmy usando one-hot-encoder.

* Mezclar un dataset.

* Crear subconjuntos de datos.

## Preparacion

In [2]:
import pandas as pd

## Carga de datos

In [3]:
iris_flowers = pd.read_csv(
    "https://raw.githubusercontent.com/jdvelasq/datalabs/master/datasets/iris.csv",
    sep = ',',         
    thousands = None,  
    decimal = '.')     

iris_flowers.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Creación de variables dummy

In [4]:
iris_flowers_dummies = pd.concat(
    [
        iris_flowers,
        pd.get_dummies(iris_flowers.Species),
    ],
    axis = 1,
)
iris_flowers_dummies

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,0,0,1
146,6.3,2.5,5.0,1.9,virginica,0,0,1
147,6.5,3.0,5.2,2.0,virginica,0,0,1
148,6.2,3.4,5.4,2.3,virginica,0,0,1
149,5.9,3.0,5.1,1.8,virginica,0,0,1

## Mezcla de dataset

In [5]:
iris_flowers_dummies = iris_flowers_dummies.sample(frac = 1)
iris_flowers_dummies

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,setosa,versicolor,virginica
60,5.0,2.0,3.5,1.0,versicolor,0,1,0
135,7.7,3.0,6.1,2.3,virginica,0,0,1
136,6.3,3.4,5.6,2.4,virginica,0,0,1
97,6.2,2.9,4.3,1.3,versicolor,0,1,0
5,5.4,3.9,1.7,0.4,setosa,1,0,0
...,...,...,...,...,...,...,...,...
19,5.1,3.8,1.5,0.3,setosa,1,0,0
26,5.0,3.4,1.6,0.4,setosa,1,0,0
114,5.8,2.8,5.1,2.4,virginica,0,0,1
35,5.0,3.2,1.2,0.2,setosa,1,0,0
144,6.7,3.3,5.7,2.5,virginica,0,0,1

## Subconjuntos de datos

In [6]:
iris_flowers_dummies_train =  iris_flowers_dummies.sample(frac = 0.8)
iris_flowers_dummies_train

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,setosa,versicolor,virginica
75,6.6,3.0,4.4,1.4,versicolor,0,1,0
10,5.4,3.7,1.5,0.2,setosa,1,0,0
34,4.9,3.1,1.5,0.2,setosa,1,0,0
85,6.0,3.4,4.5,1.6,versicolor,0,1,0
25,5.0,3.0,1.6,0.2,setosa,1,0,0
...,...,...,...,...,...,...,...,...
132,6.4,2.8,5.6,2.2,virginica,0,0,1
89,5.5,2.5,4.0,1.3,versicolor,0,1,0
77,6.7,3.0,5.0,1.7,versicolor,0,1,0
24,4.8,3.4,1.9,0.2,setosa,1,0,0
50,7.0,3.2,4.7,1.4,versicolor,0,1,0

In [7]:
iris_flowers_dummies_test = iris_flowers_dummies.drop(iris_flowers_dummies_train.index)
iris_flowers_dummies_test

,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,setosa,versicolor,virginica
63,6.1,2.9,4.7,1.4,versicolor,0,1,0
40,5.0,3.5,1.3,0.3,setosa,1,0,0
112,6.8,3.0,5.5,2.1,virginica,0,0,1
22,4.6,3.6,1.0,0.2,setosa,1,0,0
100,6.3,3.3,6.0,2.5,virginica,0,0,1
66,5.6,3.0,4.5,1.5,versicolor,0,1,0
107,7.3,2.9,6.3,1.8,virginica,0,0,1
59,5.2,2.7,3.9,1.4,versicolor,0,1,0
71,6.1,2.8,4.0,1.3,versicolor,0,1,0
29,4.7,3.2,1.6,0.2,setosa,1,0,0
84,5.4,3.0,4.5,1.5,versicolor,0,1,0
119,6.0,2.2,5.0,1.5,virginica,0,0,1
55,5.7,2.8,4.5,1.3,versicolor,0,1,0
131,7.9,3.8,6.4,2.0,virginica,0,0,1
82,5.8,2.7,3.9,1.2,versicolor,0,1,0
33,5.5,4.2,1.4,0.2,setosa,1,0,0
125,7.2,3.2,6.0,1.8,virginica,0,0,1
140,6.7,3.1,5.6,2.4,virginica,0,0,1
44,5.1,3.8,1.9,0.4,setosa,1,0,0
69,5.6,2.5,3.9,1.1,versicolor,0,1,0
91,6.1,3.0,4.6,1.4,versicolor,0,1,0
13,4.3,3.0,1.1,0.1,setosa,1,0,0
110,6.5,3.2,5.1,2.0,virginica,0,0,1
101,5.8,2.7,5.1,1.9,virginica,0,0,1
39,5.1,3.4,1.5,0.2,setosa,1,0,0
102,7.1,3.0,5.9,2.1,virginica,0,0,1
21,5.1,3.7,1.5,0.4,setosa,1,0,0
19,5.1,3.8,1.5,0.3,setosa,1,0,0
35,5.0,3.2,1.2,0.2,setosa,1,0,0
144,6.7,3.3,5.7,2.5,virginica,0,0,1