Definición de probabilidad y sus aplicaciones: Algoritmo 1R --- 34:29 min
===

* 34:29 min | Ultima modificación: Marzo 21, 2021 | [YouTube](https://youtu.be/IPGUzh1TgkI)

Las técnicas de clasificación son utilizadas para resolver problemas en los cuales se debe determinar a cual clase pertenece una instancia a partir de los valores de sus atributos; entre los casos prácticos de aplicación se encuentran: el diagnóstico de enfermedades (el paciente tiene o no la enfermedad), la detección de fraudes, los sistemas de reconocimiento (el objeto es o no es una persona), el riesgo crediticio (el solicitante pagará o no pagará la deuda). En este tutorial se presenta el algoritmo 1R, el cual permite construir un clasificador de referencia basado en reglas de asociación, y contra el cual se pueden contrastar los resultados de otros algoritmos más complejos.

## Descripción del problema

El problema abordado se desea determina a que clase pertenece una nueva observación ($A$, $B$ o $C$), con base en una muestra de observaciones recolectada previamente.

Se tiene un conjunto ficticio de 15 ejemplos para los cuales se tienen tres características $x_1$, $x_2$ y $x_3$ y su respectiva clase. Se desea determinar a que clase pertenece un nuevo punto con coordenadas $x_1$, $x_2$ y $x_3$. Si las clases representan la presencia (o no) de una enfermedad, las variables $x_i$ prodian representan, por ejemplo, los resultados de los exámenes médicos de los pacientes.

In [1]:
%%writefile /tmp/data.csv
x1,x2,x3,y
a,e,h,A
a,e,i,C
a,e,j,B
a,f,h,A
a,f,i,A
a,g,h,A
a,g,h,B
b,e,i,B
b,f,i,B
b,f,j,B
b,g,j,C
c,e,i,C
c,f,j,C
c,g,h,B
c,g,i,B
c,g,j,C
d,f,j,A
d,g,j,A

Overwriting /tmp/data.csv

## Definición de probabilidad como frecuencia

**Espacio muestral:** se define como el conjunto de todos los posibles resultados de un experimento.

**Pregunta.---** En la tirada de dos dados, ¿cuál es el espacio muestral?

**Evento:** Es cualquier colección de posibles resultados de un experimento (subconjunto del espacio muestral).

En su forma más simple, el concepto de probabilidad puede interpretarse como la frecuencia con que ocurre un evento. Por ejempo, si en la tirada de dos dados se definen como un evento la cantidad de posibles resultados que dan una suma determinada, entonces:

![tirada-dados](assets/tirada-dados.jpg)


    Pr(𝑋= 2) = 1 / 36   Pr(𝑋= 6) = 5 / 36   Pr(𝑋=10) = 3 / 36
    Pr(𝑋= 3) = 2 / 36   Pr(𝑋= 7) = 6 / 36   Pr(𝑋=11) = 2 / 36
    Pr(𝑋= 4) = 3 / 36   Pr(𝑋= 8) = 5 / 36   Pr(𝑋=12) = 1 / 36
    Pr(𝑋= 5) = 4 / 36   Pr(𝑋= 9) = 4 / 36

## Propiedades y definiciones básicas sobre probabilidad


* Todas las probabilidades deben estar entre $0$ y $1$: 


$$0 \le \text{Pr}(x_i) \le 1$$


* Las probabilidades de eventos mutuamente exclusivos (no pueden ocurrir simultáneamente) y colectivamente exhaustivos (cubren todo el universo de casos posibles) deben sumar la unidad:

$$\sum_{i=1}^n \text{Pr}(x_i) = 1$$


* Probabilidad condicional $\text{Pr}(A \; | \; B)$: probabilidad de que ocurra un evento $A$ sabiendo que otro evento $B$ ya ocurrio.


* Independencia: Si los eventos $A$ y $B$ son independientes:

$$\text{Pr}(A \; |  \; B) = \text{Pr}(A)$$

## Reglas de asociación para clasificación

La metodología 1R se basa en la partición del espacio de entrada usando una y sólo una de las variables (atributos) del problema. Para el problema planteado, una regla basada en el atributo `x1` podría ser:

    if x1 in {a, d}:  y = A
    if x1 in {b}:     y = B
    if x1 in {c}:     y = C

El algoritmo funciona de la siguiente forma: se toma el primer atributo $x_1$ y se divide en grupos por cada  valor que puede tomar dicho atributo, es decir, por `a`, `b`, `c`, y `d`; para cada atributo se determina a que clase es más probable que pertenezca los ejemplos y se asigna dicha clase a dicho atributo. Es decir, para cada atributo se cuentan cuántos ejemplos hay de cada categoría y se asigna la clase por mayoría, esto es, si hay cuatro ejemplos para la categoría `a` de $x_1$ y tres de ellos pertencen a la clase `A` y el restante a `C` se dice que `if x1 == a: y = A`; esto equivale a decir que si `x1 == a` es más probable que el ejemplo pertenezca a la clase sea `A`. Así, el clasificador basado en este atributo podría ser escrito como un sistema de reglas:

         #   x1   x2   x3    y  
    --------------------------

    if x1 == a:  y = A
    
         1    a    g    h    A
         2    a    e    i    A
         3    a    f    h    A
        11    a    e    i    C
        
    if x1 == b:  y = B
    
         6    b    e    i    B 
         7    b    f    i    B
        12    b    g    j    C
         8    b    f    i    B

    if x1 == c:  y = C
    
         9    c    g    h    B
        10    c    g    h    B        
        13    c    f    j    C
        14    c    g    h    C
        15    c    e    i    C
    
    if x1 == d:  y = A

         4    d    f    j    A
         5    d    g    j    A

       
Al agrupar por $x_1$, este conjunto de reglas se reescribe como:

    if x1 in {a, d}:
        y = A
    elif x1 in {b}:
        y = B
    else:
        y = C
        
Para el clasificador anterior se puede calcular una métrica de error.

Luego se toma el segundo atributo $x_2$ y se procede de igual forma para construir otro clasificador. El proceso se repite hasta obtener un clasificador por cada atributo. Se escoge el clasificador con mayor precisión.

## Métricas de desempeño de clasificadores

Para evaluar el desempeño en problemas de clasificación dicotómicos (dos clases mutuamente excluyentes) se usa la matriz de confusión:


             | Pronostico
             |  P     N
    ---------|------------  
          P  |  TP    FN          
    Real     |
          N  |  FP    TN
    
    TP - Verdadero positivo (correcto)
    TN - Verdadero negativo (correcto)
    FN - Falso negativo (mal clasificado)
    FP - Falso positivo (mal clasificado)
    
Esta tabla permite analizar el comportamiento del modelo.

La medición de la precisión del modelo permite estimar el desempeño del modelo ante nuevos datos.

* Tasa de éxito (porcentaje de patrones clasificados correctamente):


$$\text{success rate} = \frac{\text{TP} + \text{TN}}{\text{TP} + \text{TN} + \text{FP} + \text{FN}}$$

* Tasa de error (porcentaje total de patrones clasificados incorrectamente):

$$\text{error rate} = \frac{\text{FP} + \text{FN}}{\text{TP} + \text{TN} + \text{FP} + \text{FN}} = 1 - \text{accuracy}$$

* Precisión o valor predictivo positivo: Proporción de casos positivos que fueron verdaderamente positivos.


$$\text{precision} = \frac{\text{TP}}{\text{TP}  + \text{FP}}$$

* Valor predictivo negativo: Proporción de casos negativos que fueron verdaderamente negativos.


$$\text{negative predictive value} = \frac{\text{TN}}{\text{TN}  + \text{FN}}$$

* Sensibilidad, tasa verdadera positiva, recall: mide la proporción de ejemplos positivos que fueron correctamente clasificados.


$$\text{sensitibity} = \frac{\text{TP}}{\text{TP}  + \text{FN}}$$

* Especifidad o tasa verdadera negativa: mide la proporción de ejemplos negativos correctamente clasificados.


$$\text{specifity} = \frac{\text{TN}}{\text{TN}  + \text{FP}}$$

**Actividad.---** Para el ejemplo planteado, calcule las métricas de error descritas.

**Actividad.---** Escriba un clasificador de una regla para el siguiente problema y cómpute la matriz de confusión para el mejor modelo encontrado.

![assets/tree-exercise.jpg](assets/tree-exercise.jpg)

## Solución en Python

### Preparación y carga de datos

In [2]:
#
# Preparación
#
import pandas as pd

In [3]:
#
# Carga el archivo como un DataFrame
#
df = pd.read_csv(
    "/tmp/data.csv",
    sep=",",  
    thousands=None,
    decimal=".",
)

df.head()

  x1 x2 x3  y
0  a  e  h  A
1  a  e  i  C
2  a  e  j  B
3  a  f  h  A
4  a  f  i  A

### Generación de las reglas

In [4]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    return df0


oneR_fit(df, "x1", "y")

   x1 x2 x3  y  counter
0   a  e  h  A        0
1   a  e  i  C        0
2   a  e  j  B        0
3   a  f  h  A        0
4   a  f  i  A        0
5   a  g  h  A        0
6   a  g  h  B        0
7   b  e  i  B        0
8   b  f  i  B        0
9   b  f  j  B        0
10  b  g  j  C        0
11  c  e  i  C        0
12  c  f  j  C        0
13  c  g  h  B        0
14  c  g  i  B        0
15  c  g  j  C        0
16  d  f  j  A        0
17  d  g  j  A        0

In [5]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    return df0


oneR_fit(df, "x1", "y")

  x1  y  counter
0  a  A        4
1  a  B        2
2  a  C        1
3  b  B        3
4  b  C        1
5  c  B        2
6  c  C        3
7  d  A        2

In [6]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)
    return df0_max_counter


oneR_fit(df, "x1", "y")

   counter
0        4
1        4
2        4
3        3
4        3
5        3
6        3
7        2

In [7]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)
    df0_idx = df0["counter"] == df0_max_counter["counter"]
    return df0_idx


oneR_fit(df, "x1", "y")

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7     True
Name: counter, dtype: bool

In [8]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)
    df0_idx = df0["counter"] == df0_max_counter["counter"]
    df0 = df0.loc[df0_idx, [var, target]]
    return df0


oneR_fit(df, "x1", "y")

  x1  y
0  a  A
3  b  B
6  c  C
7  d  A

In [9]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)
    df0_idx = df0["counter"] == df0_max_counter["counter"]
    df0 = df0.loc[df0_idx, [var, target]]
    df0 = df0.groupby(var, as_index=False).first()
    return df0


oneR_fit(df, "x1", "y")

  x1  y
0  a  A
1  b  B
2  c  C
3  d  A

In [10]:
def oneR_fit(df, var, target):
    df0 = df.copy()
    df0["counter"] = 0
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)
    df0_idx = df0["counter"] == df0_max_counter["counter"]
    df0 = df0.loc[df0_idx, [var, target]]
    df0 = df0.groupby(var, as_index=False).first()
    df0 = df0.set_index(var)
    return df0


oneR_fit(df, "x1", "y")

    y
x1
a   A
b   B
c   C
d   A

In [11]:
#
# Versión final con comentarios
#
def oneR_fit(df, var, target):
    # df: pandas DataFrame
    # var: nombre de la columna para construir el clasificador
    # target: columna con las clases

    ## crea una copia para no modificar el df original
    df0 = df.copy()

    ## Columna para contar la cantidad de ocurrencias del target
    df0["counter"] = 0

    ## conteo
    df0 = df0.groupby([var, target], as_index=False).count()[[var, target, "counter"]]

    ## genera un vector con el maximo conteo por cada valor de var
    df0_max_counter = df0.groupby([var], as_index=False)["counter"].transform(max)

    ## vector de T/F indicando si la fila contiene el valor maximo del conteo
    df0_idx = df0["counter"] == df0_max_counter["counter"]

    ## Seleccionar var y target para los maximos
    df0 = df0.loc[df0_idx, [var, target]]

    ## obtiene solo la primera fila si varias clases
    ## tiene la misma frecuencia maxima
    df0 = df0.groupby(var, as_index=False).first()

    ## convierte var en el indice de la tabla
    df0 = df0.set_index(var)

    return df0

In [12]:
## reglas para x1
rules_x1 = oneR_fit(df, "x1", "y")
rules_x1

    y
x1
a   A
b   B
c   C
d   A

In [13]:
## reglas para x2
rules_x2 = oneR_fit(df, "x2", "y")
rules_x2

    y
x2
e   B
f   A
g   B

In [14]:
## reglas para x3
rules_x3 = oneR_fit(df, "x3", "y")
rules_x3

    y
x3
h   A
i   B
j   C

### Predicción

In [15]:
def oneR_predict(df, rules):
    df0 = df.copy()
    df0 = df0.set_index(rules.index.name, drop=False)
    return df0


oneR_predict(df.copy(), rules_x1)

   x1 x2 x3  y
x1
a   a  e  h  A
a   a  e  i  C
a   a  e  j  B
a   a  f  h  A
a   a  f  i  A
a   a  g  h  A
a   a  g  h  B
b   b  e  i  B
b   b  f  i  B
b   b  f  j  B
b   b  g  j  C
c   c  e  i  C
c   c  f  j  C
c   c  g  h  B
c   c  g  i  B
c   c  g  j  C
d   d  f  j  A
d   d  g  j  A

In [16]:
def oneR_predict(df, rules):
    df0 = df.copy()
    df0 = df0.set_index(rules.index.name, drop=False)
    df0 = df0.join(rules, rsuffix="_predicted_" + rules.index.name)
    return df0


oneR_predict(df.copy(), rules_x1)

   x1 x2 x3  y y_predicted_x1
x1
a   a  e  h  A              A
a   a  e  i  C              A
a   a  e  j  B              A
a   a  f  h  A              A
a   a  f  i  A              A
a   a  g  h  A              A
a   a  g  h  B              A
b   b  e  i  B              B
b   b  f  i  B              B
b   b  f  j  B              B
b   b  g  j  C              B
c   c  e  i  C              C
c   c  f  j  C              C
c   c  g  h  B              C
c   c  g  i  B              C
c   c  g  j  C              C
d   d  f  j  A              A
d   d  g  j  A              A

In [17]:
def oneR_predict(df, rules):
    df0 = df.copy()
    df0 = df0.set_index(rules.index.name, drop=False)
    df0 = df0.join(rules, rsuffix="_predicted_" + rules.index.name)
    df0.index = range(len(df0))
    return df0


oneR_predict(df.copy(), rules_x1)

   x1 x2 x3  y y_predicted_x1
0   a  e  h  A              A
1   a  e  i  C              A
2   a  e  j  B              A
3   a  f  h  A              A
4   a  f  i  A              A
5   a  g  h  A              A
6   a  g  h  B              A
7   b  e  i  B              B
8   b  f  i  B              B
9   b  f  j  B              B
10  b  g  j  C              B
11  c  e  i  C              C
12  c  f  j  C              C
13  c  g  h  B              C
14  c  g  i  B              C
15  c  g  j  C              C
16  d  f  j  A              A
17  d  g  j  A              A

In [18]:
#
# Versión final comentada
#
def oneR_predict(df, rules):
    ## genera una copia del DataFrame
    df0 = df.copy()

    ## convierte la variable usada para construir las reglas
    ## en el indice de las filas del dataframe
    df0 = df0.set_index(rules.index.name, drop=False)

    ## hace un left join con base en los valores de los
    ## indices de las filas del df y rules
    df0 = df0.join(rules, rsuffix="_predicted_" + rules.index.name)
    df0.index = range(len(df0))

    return df0

In [19]:
df0 = df.copy()
df0 = oneR_predict(df0, rules_x1)  ## Pronostico usando x1
df0 = oneR_predict(df0, rules_x2)  ## Pronostico usando x2
df0 = oneR_predict(df0, rules_x3)  ## Pronostico usando x3
df0

   x1 x2 x3  y y_predicted_x1 y_predicted_x2 y_predicted_x3
0   a  e  h  A              A              B              A
1   a  f  h  A              A              A              A
2   a  g  h  A              A              B              A
3   a  g  h  B              A              B              A
4   c  g  h  B              C              B              A
5   a  e  i  C              A              B              B
6   b  e  i  B              B              B              B
7   c  e  i  C              C              B              B
8   a  f  i  A              A              A              B
9   b  f  i  B              B              A              B
10  c  g  i  B              C              B              B
11  a  e  j  B              A              B              C
12  b  f  j  B              B              A              C
13  c  f  j  C              C              A              C
14  d  f  j  A              A              A              C
15  b  g  j  C              B              B              C
16  c  g  j  C              C              B              C
17  d  g  j  A              A              B              C

### Precisión

In [20]:
## cantidad de aciertos
print("x1 : ", (df0.y == df0.y_predicted_x1).sum())
print("x2 : ", (df0.y == df0.y_predicted_x2).sum())
print("x3 : ", (df0.y == df0.y_predicted_x3).sum())

x1 :  12
x2 :  8
x3 :  9

### Matriz de confusión

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(df0.y, df0.y_predicted_x1)

array([[6, 0, 0],
       [2, 3, 2],
       [1, 1, 3]])

In [22]:
confusion_matrix(df0.y, df0.y_predicted_x2)

array([[3, 3, 0],
       [2, 5, 0],
       [1, 4, 0]])

In [23]:
confusion_matrix(df0.y, df0.y_predicted_x3)

array([[3, 1, 2],
       [2, 3, 2],
       [0, 2, 3]])